### ISSUE TITLE
Non-functional mods

### ISSUE THREAD

**Issue by bruvmode** [fifty-six/Scarab#104]
### Scarab Version

1.19

### Hollow Knight Version

1.5.78.11833

### Steps to Reproduce

attempted to unzip scarab to a folder on desktop using WinRAR, the folder does not appear, after downloading mods(While scarab was within the ZIP file still) and starting the game via steam, no mod functionalities were observed and there was no sign of any of the mods I installed, even after searching the options menu
![Screenshot (7)](https://user-images.githubusercontent.com/79219197/185654370-da718c51-5246-432a-9f6b-a830d1765884.png)
![Screenshot (8)](https://user-images.githubusercontent.com/79219197/185654435-0da70271-778c-44e4-840d-65326b43d8fc.png)
Images are my downloaded mods, both within the Hollow Knight folder and within the mod manager

### Expected Behaviour

I expected the game to boot and the mods to function as normal

### Actual Behaviour

Mods had no effect on the game, and it was as if i had a vanilla hollow knight installation

### Logs

Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #40902273)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #32576140)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24749807)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #20917673)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #54041329)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #16609919)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58602024)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57656175)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #49143529)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #35528341)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #51319614)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #59223347)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Settings doesn't exist. Creating it at detected path ValidPath { Root = C:\Program Files (x86)/Steam/steamapps/common/Hollow Knight, Suffix = hollow_knight_Data/Managed }.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57434139)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #47145209)
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model

**Comment by fifty-six** [comment]
Could I see your Managed folder? Looks like the API just installed wrong. Do you have several installations also?

**Comment by bruvmode** [comment]
I actually found the solution, and the cause of the issue
I ran scarab from within the zip file, and was unable to extract it into a folder using WinRAR(cause)
simply manually drag and drop the files from the zip to your desktop, then run scarab and change the hollow knight folder, even if to what it was before(solution)
