### ISSUE TITLE
Text is unreadable on HiDPI display

### ISSUE THREAD

**Issue by l0b0** [fifty-six/Scarab#109]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

N/A

### Steps to Reproduce

Run `Scarab`

### Expected Behaviour

The text in the main window should be readable.

### Actual Behaviour

The text in the main window doesn't scale with the GNOME display scaling (set to 200% in my case).

### Logs

N/A

**Comment by fifty-six** [comment]
Do you happen to have any pictures? Are you on Wayland or X11?

**Comment by l0b0** [comment]
I'm currently on Wayland. My resolution is 3840x2160, and the application is showing up as a 710 × 560 pixel window: ![Screenshot from 2022-10-06 10-05-57](https://user-images.githubusercontent.com/168301/194163663-40db18d9-493f-402b-882c-80d2c6a17271.png)

**Comment by fifty-six** [comment]
Does resizing leave the font size the same?

**Comment by l0b0** [comment]
Yep: 
![Screenshot from 2022-10-06 10-10-48](https://user-images.githubusercontent.com/168301/194164442-f989e7a3-325b-4db9-8758-1707f384955e.png)

**Comment by l0b0** [comment]
I tried [`AVALONIA_SCREEN_SCALE_FACTORS=XWAYLAND0=2 Scarab` as suggested elsewhere](https://github.com/AvaloniaUI/Avalonia/issues/6923#issuecomment-1046349970), but that doesn't seem to do anything.

**Comment by l0b0** [comment]
Also tried with no discernible difference:

- Logging in with X11 rather than Wayland.
- Running `AVALONIA_SCREEN_SCALE_FACTORS=DisplayPort-2=2 Scarab` in X11

**Comment by fifty-six** [comment]
![image](https://user-images.githubusercontent.com/10470872/205424538-d753c164-62e0-48ca-bd2f-d078c3ba2d09.png)
It seems to be scaled for me on Wayland with river (4k monitor, 2x scale). Does `wlr-randr` report the display having `Scale: 2.00000`? Sorry this took so long, have been very busy

**Comment by l0b0** [comment]
With:

- Scarab 1.19.0.0
- NixOS 22.11
- 4k screen
- GNOME display scale set to 200%
- Wayland

Scarab does not scale. `wlr-randr` says

> compositor doesn't support wlr-output-management-unstable-v1

**Comment by fifty-six** [comment]
Alright, I'll get gnome and try this out when I get the chance - might be a bit as finals are next week

**Comment by l0b0** [comment]
> Alright, I'll get gnome and try this out when I get the chance - might be a bit as finals are next week

Thank you, and good luck with the finals!

**Comment by fifty-six** [comment]
Sorry, it took me *way* too long to get around to this - but when I try Scarab under `mutter` (gnome's WM) with a debug monitor scale of 2 or 4 I can reproduce (somewhat) similar results. ![image](https://user-images.githubusercontent.com/10470872/229036725-b417250f-d587-47e8-bbeb-2f4d75198b20.png)
Other applications respect the scale properly, but for whatever reason Scarab doesn't. 

On wlroots based compositors it seems to work fine - 
![image](https://user-images.githubusercontent.com/10470872/229037007-d14568d2-d286-43b6-a9cf-84be69688def.png).

*However*, I did have luck with `AVALONIA_SCREEN_SCALE_FACTORS`. 
![image](https://user-images.githubusercontent.com/10470872/229038526-a09c460a-2601-47e8-8ea2-17d2eb72c3bf.png)
Interestingly enough, it didn't have `XWAYLAND0/1/...` as the display name. 

So I then went and looked back at `xrandr`'s active displays on river... 
```bash
% xrandr --listactivemonitors
Monitors: 3
 0: +DP-2 1920/620x1080/340+1920+0  DP-2
 1: +DP-3 2560/600x1440/340+3840+0  DP-3
 2: +HDMI-A-1 1920/480x1080/270+0+0  HDMI-A-1
%                                                                                                                       ~
```
and it seems to just fake actual monitors, which would explain the scaling working (somewhat) correctly. `DP-3` is actually my 4k display.

So, the question I have at the end of this is, are you sure it's `XWAYLAND0` that Scarab is running on? When you run `xrandr --listactivemonitors` is that the only one there?

If you're curious by the way, you can try nested mutter as follows 
```bash
MUTTER_DEBUG_DUMMY_MONITOR_SCALES=2 MUTTER_DEBUG_DUMMY_MODE_SPECS=1920x1080 mutter --wayland --nested -- alacritty
```
(alacritty just being for the sake of it being easier to launch applications, you could replace it with whatever.)

**Comment by l0b0** [comment]
Thanks for looking into this! I only have a single monitor:

```console
$ xrandr --listactivemonitors
Monitors: 1
 0: +*XWAYLAND27 3840/940x2160/530+0+0  XWAYLAND27
```

It looks like monitor numbering must've changed recently, because it really was on XWAYLAND0 before. :shrug: 

I don't have alacritty, mutter, or avalonia installed.

I'm going to completely randomly guess that the problem is with whatever GUI framework Scarab is using. Does their official documentation have any info about supporting display scaling?

**Comment by fifty-six** [comment]
The GUI framework is Avalonia to be clear, so the [thing linked to by the issue you found](https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI) is basically all. Could you double check that with `AVALONIA_SCREEN_SCALE_FACTORS="XWAYLAND27=2" ./../wherever/Scarab` the scaling doesn't work and that with it running `XWAYLAND27` is still the only active display in `xrandr`?

**Comment by l0b0** [comment]
Sorry, `AVALONIA_SCREEN_SCALE_FACTORS="XWAYLAND27=2" Scarab` doesn't scale the windows, and `xrandr --listactivemonitors` while Scarab is running still reports XWAYLAND27 as the only active display.

**Comment by l0b0** [comment]
Sorry, `AVALONIA_SCREEN_SCALE_FACTORS="XWAYLAND27=2" Scarab` doesn't scale the windows, and `xrandr --listactivemonitors` while Scarab is running still reports XWAYLAND27 as the only active display.

I'm running [Scarab 1.19.0.0](https://github.com/NixOS/nixpkgs/pull/184413) though, so I should probably upgrade.

**Comment by fifty-six** [comment]
Could you try running it under `MUTTER_DEBUG_DUMMY_MONITOR_SCALES=2 MUTTER_DEBUG_DUMMY_MODE_SPECS=1920x1080 mutter --wayland --nested -- terminal` (`terminal` being your terminal of choice)? You'd still check `xrandr --listactivemonitors` there and set the variable, but I'm curious as to whether it doesn't manifest in nested stuff or in just `mutter` itself. `mutter` is part of GNOME (it's `gnome.mutter` in nixpkgs), so you should have it.  `1.19.0.0` shouldn't be any different wrt this issue, though I'd still recommend upgrading when you get the chance.

**Comment by l0b0** [comment]
Main console output:

```console
$ MUTTER_DEBUG_DUMMY_MONITOR_SCALES=2 MUTTER_DEBUG_DUMMY_MODE_SPECS=1920x1080 mutter --wayland --nested -- gnome-terminal
libmutter-Message: 20:12:44.424: Running Mutter (using mutter 43.2) as a Wayland display server
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
libmutter-Message: 20:12:44.498: Using public X11 display :2, (using :3 for managed services)

(mutter:690995): libmutter-WARNING **: 20:12:44.498: WL: unable to lock lockfile /run/user/1000/wayland-0.lock, maybe another compositor is running

libmutter-Message: 20:12:44.498: Using Wayland display name 'wayland-1'

(mutter:690995): libmutter-WARNING **: 20:12:44.510: Lost or failed to acquire name org.gnome.Mutter.ScreenCast

(mutter:690995): libmutter-WARNING **: 20:12:44.510: Lost or failed to acquire name org.gnome.Mutter.RemoteDesktop
```

Terminal output inside `mutter`:

```console
$ xrandr --listactivemonitors
Can't open display :2
```

Scarab crashed. From the error log:

```text
System.Exception: XOpenDisplay failed
   at Avalonia.X11.AvaloniaX11Platform.Initialize(X11PlatformOptions options) in /_/src/Avalonia.X11/X11Platform.cs:line 57
   at Avalonia.AvaloniaX11PlatformExtensions.<>c__0`1.<UseX11>b__0_0() in /_/src/Avalonia.X11/X11Platform.cs:line 279
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 303
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Scarab.Program.Main(String[] args) in /build/source/Scarab/Program.cs:line 27
```

**Comment by fifty-six** [comment]
Oh, hmm. If you wanted, you could try `sway` or `river` or similar and see if that works, though I'd understand if that's too much effort. If it is I can try running gnome non-nested a bit later and then go from there. I checked straight up GNOME instead of nested in case that was the issue, but it seems to work for me with the variables set, strangely enough. 
![sshot](https://user-images.githubusercontent.com/10470872/229054031-e9bf85db-a14f-475c-96dd-746066e23794.png)

**Comment by l0b0** [comment]
FYI ~~[`AVALONIA_GLOBAL_SCALE_FACTOR=2 Scarab`](https://github.com/AvaloniaUI/Avalonia/issues/9390#issuecomment-2382126451) works on GNOME+Wayland.~~ No longer, see below.

**Comment by l0b0** [comment]
Welp, `AVALONIA_GLOBAL_SCALE_FACTOR=2 Scarab` no longer works with 2.7.0.0 - compare the terminal to Scarab:

<img width="1920" height="1056" alt="Image" src="https://github.com/user-attachments/assets/c14fe038-3094-4e2d-8890-1710d45375b2" />

No idea whether this is related to the [latest dependencies/build config](https://github.com/NixOS/nixpkgs/commit/043466c4d57807f78f9daa3439bbd512db3d3525), newer GNOME, kernel, or what.

**Comment by fifty-six** [comment]
🥀. My main monitor is 2x now I believe so I can take another look at this maybe?

**Comment by l0b0** [comment]
That would be great! FWIW, it should be possible to test with any size monitor.

**Comment by fifty-six** [comment]
Yeah that's true, just particularly convenient now
