### ISSUE TITLE
does not launch

### ISSUE THREAD

**Issue by ravewyvern** [fifty-six/Scarab#122]
### Scarab Version

v1.19.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

1. run the app

### Expected Behaviour

it to launch and for me to be able to install mods

### Actual Behaviour

it didnt launch and gave me an error as a file on the desktop

### Logs

System.TypeInitializationException: The type initializer for 'SkiaSharp.SKImageInfo' threw an exception.
 ---> System.DllNotFoundException: Dll was not found.
   at SkiaSharp.SkiaApi.sk_colortype_get_default_8888()
   at SkiaSharp.SKImageInfo..cctor()
   --- End of inner exception stack trace ---
   at Avalonia.Skia.PlatformRenderInterface..ctor(ISkiaGpu skiaGpu, Nullable`1 maxResourceBytes) in /_/src/Skia/Avalonia.Skia/PlatformRenderInterface.cs:line 27
   at Avalonia.Skia.SkiaPlatform.Initialize(SkiaOptions options) in /_/src/Skia/Avalonia.Skia/SkiaPlatform.cs:line 20
   at Avalonia.SkiaApplicationExtensions.<>c__0`1.<UseSkia>b__0_0() in /_/src/Skia/Avalonia.Skia/SkiaApplicationExtensions.cs:line 20
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 304
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Scarab.Program.Main(String[] args)

**Comment by fifty-six** [comment]
What OS was this on?

**Comment by ravewyvern** [comment]
Windows 11

**Comment by fifty-six** [comment]
You downloaded the full executable from releases, right? Did you extract the zip fully before running it?

**Comment by Fexeyexz** [comment]
да
