### ISSUE TITLE
Texts in popups are a bunch of boxes

### ISSUE THREAD

**Issue by CarrieForle** [fifty-six/Scarab#143]
### Scarab Version

v1.31.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

1. Open scarab.exe downloaded from windows.zip
2. A popup filled with boxes would appear.
3. Clicking "open" button will open a dialog to choose the folder where Hollow Knight is installed, which won't let me bypass even when I select the hollow_knight_Data folder or its parent folder.

(Note: This probably can't be reproducible without setting your Windows language to Chinese (Traditional), which is the language I'm running on my Windows 10, as I speculate this is a localisation issue.)

### Expected Behaviour

Open Scarab as usual.

### What I see in step 2
![圖片](https://user-images.githubusercontent.com/53133715/228284972-e3298593-b5e2-474e-8845-afb61ef30053.png)
### What I see in step 3
![圖片](https://user-images.githubusercontent.com/53133715/228284937-5ee80a07-da3b-4272-913f-917f175eed52.png)

### Logs

```Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #40902273)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #32576140)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24749807)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #62608109)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #26602077)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #38092103)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #35632012)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #52252659)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #511887)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #17349988)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21932166)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #63171767)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #10309404)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #25675773)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #29755367)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #49998812)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #47336128)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #23371976)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #37626701)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #3095993)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #27863937)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #26691149)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #38893755)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #14499481)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #18303590)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #30514590)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #6195855)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #32610412)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #25058257)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24197721)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #18495050)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #32237730)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21704116)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21421675)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57434139)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #6956456)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #62608109)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #26602077)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #511887)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #4606985)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #41462866)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #36052245)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #56034750)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #34550710)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21421675)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57434139)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #62608109)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #26602077)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #38092103)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #12001237)
Installer out of date! Version 1.20.0.0 with latest 1.31.0.0!
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #52136803)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #66578044)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #62331491)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #63406242)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #33785274)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #35632012)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #7670737)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #1927776)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #17349988)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #12001237)
Installer out of date! Version 1.19.0.0 with latest 1.31.0.0!
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #52136803)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #66578044)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #62331491)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #9433441)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #17792110)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #25911262)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #63248075)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #32361769)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #22820469)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #54897010)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24311045)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #17472816)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24129853)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #15842089)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #8361080)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #47136405)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21574462)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #59952436)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #49877601)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #46245228)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #13553869)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57434139)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #47145209)```

**Comment by fifty-six** [comment]
Thanks for the detailed report. Looks like I need to set the font according to this avalonia issue - https://github.com/AvaloniaUI/Avalonia/issues/3522, I'll look into it when I can

**Comment by CarrieForle** [comment]
> Hey, does this still happen to be the case?

Hello. The issue is solved with the new version. Thank you!
