### ISSUE TITLE
File not found/doesn't want to connect

### ISSUE THREAD

**Issue by Throomtroom** [fifty-six/Scarab#152]
### Scarab Version

v1.31.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

open the program

### Expected Behaviour

scarab recognize my Hollow Knight_data file and connect to it 

### Actual Behaviour

It does'nt recognize at all even when I choose the file manually and my game has a black screen so I have to uninstall my game

### Logs

Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Settings doesn't exist. Creating it at detected path ValidPath { Root = C:\Program Files (x86)/GOG Galaxy/Games/Hollow Knight, Suffix = Hollow Knight_Data/Managed }.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21421675)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57434139)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #53182860)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #8883693)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #12844374)
Something sent a shutdown event, calling Application.Shutdown
Got past Application.Shutdown, did shutting down fail?

**Comment by Throomtroom** [comment]
My issue was fixed after I did my windows update
