### ISSUE TITLE
hello everyone. this is the error I get when starting scarab

### ISSUE THREAD

**Issue by PopaMopaPonka** [fifty-six/Scarab#159]
### Scarab Version

v1.14.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

explain to me how to fix it

### Expected Behaviour

I thought it would start xD

### Actual Behaviour

I just launched Scarab and I was given this in logs

### Logs

System.EntryPointNotFoundException: Entry point was not found.
   at Avalonia.Win32.Interop.UnmanagedMethods.GetDpiForMonitor(IntPtr hmonitor, MONITOR_DPI_TYPE dpiType, UInt32& dpiX, UInt32& dpiY)
   at Avalonia.Win32.WindowImpl.CreateWindow() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 777
   at Avalonia.Win32.WindowImpl..ctor() in /_/src/Windows/Avalonia.Win32/WindowImpl.cs:line 127
   at Avalonia.Win32.Win32Platform.CreateWindow() in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 316
   at Avalonia.Controls.Platform.PlatformManager.CreateWindow() in /_/src/Avalonia.Controls/Platform/PlatformManager.cs:line 45
   at Avalonia.Controls.Window..ctor() in /_/src/Avalonia.Controls/Window.cs:line 231
   at Scarab.Views.MainWindow..ctor() in D:\a\Scarab\Scarab\Scarab\Views\MainWindow.xaml.cs:line 8
   at Scarab.App.OnFrameworkInitializationCompleted() in D:\a\Scarab\Scarab\Scarab\App.xaml.cs:line 25
   at Avalonia.Controls.AppBuilderBase`1.Setup() in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 312
   at Avalonia.Controls.AppBuilderBase`1.SetupWithLifetime(IApplicationLifetime lifetime) in /_/src/Avalonia.Controls/AppBuilderBase.cs:line 179
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 208
   at Scarab.Program.Main(String[] args) in D:\a\Scarab\Scarab\Scarab\Program.cs:line 27

**Comment by fifty-six** [comment]
Seems like an upstream thing (https://github.com/AvaloniaUI/Avalonia/issues/7284), what Windows version are you on?

**Comment by PopaMopaPonka** [comment]
fifty-six, hi. i fixed this problem

**Comment by TC5001** [comment]
How did you fix the problem?
I'm getting the same issue
