### ISSUE TITLE
Scarab doesn't open at all

### ISSUE THREAD

**Issue by Ahmadlolbit** [fifty-six/Scarab#160]
### Scarab Version

1.32.0.0

### Hollow Knight Version

1.4.2.4

### Steps to Reproduce

just as you run it as administrator a window pops up but immedietly closes itself for some reason

### Expected Behaviour

for it to open at least

### Actual Behaviour

it just closed

### Logs

Launching...
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Scarab Error: 0 : System.MissingMethodException: Attempted to access a missing method.
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulate(IServiceProvider , MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulateTrampoline(MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxStandardWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(MessageBoxStandardParams params)
   at Scarab.ViewModels.MainWindowViewModel.GetSettingsPath() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 249
   at Scarab.ViewModels.MainWindowViewModel.Impl() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 60
   at Scarab.ViewModels.MainWindowViewModel.<.ctor>b__10_0() in D:\a\Scarab\Scarab\Scarab\ViewModels\MainWindowViewModel.cs:line 287
    DateTime=2023-06-13T10:56:40.3619070Z

**Comment by fifty-six** [comment]
Just to make sure - you extracted the entire zip to a new location, right?

**Comment by Ahmadlolbit** [comment]
> Just to make sure - you extracted the entire zip to a new location, right?

Yes. I extracted into my Games folder onside of C:/, i tried it on the desktop, as administrator, without administrator, it's Windows 11 latest update, i checked drivers (they're all up to date), i checked the game itself it wasn't up to date so i updated it, nothing changed
