### ISSUE TITLE
Scarab No longer opens, mods still work but scarab opens then immediately closes.

### ISSUE THREAD

**Issue by MasterOfPendulum** [fifty-six/Scarab#165]
### Scarab Version

v1.14.0.0

### Hollow Knight Version

v1.5.78.1833

### Steps to Reproduce

Ever scince scarab 1.14 update, scarab no longer opens. 

### Expected Behaviour

Scarab to open and to see my mod list.

### Actual Behaviour

Scarab closed automatically without any user input

### Logs

ReactiveUI.UnhandledErrorException: An object implementing IHandleObservableErrors (often a ReactiveCommand or ObservableAsPropertyHelper) has errored, thereby breaking its observable pipeline. To prevent this, ensure the pipeline does not error, or Subscribe to the ThrownExceptions property of the object in question to handle the erroneous case.
 ---> System.MissingMethodException: Attempted to access a missing method.
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulate(IServiceProvider , MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.!XamlIlPopulateTrampoline(MsBoxStandardWindow )
   at MessageBox.Avalonia.Views.MsBoxStandardWindow.InitializeComponent()
   at MessageBox.Avalonia.Views.MsBoxStandardWindow..ctor()
   at MessageBox.Avalonia.MessageBoxManager.GetMessageBoxStandardWindow(MessageBoxStandardParams params)
   at Scarab.Util.PathUtil.SelectPath(Boolean fail) in D:\a\Scarab\Scarab\Scarab\Util\PathUtil.cs:line 41
   at Scarab.Util.PathUtil.SelectPathFallible() in D:\a\Scarab\Scarab\Scarab\Util\PathUtil.cs:line 20
   at Scarab.ViewModels.ModListViewModel.ChangePathAsync() in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 147
   --- End of inner exception stack trace ---
   at ReactiveUI.RxApp.<>c__DisplayClass9_0.<.cctor>b__2() in /_/src/ReactiveUI/RxApp.cs:line 109
   at System.Reactive.Concurrency.Scheduler.Invoke(Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 253
   at System.Reactive.Concurrency.Scheduler.<>c.<Schedule>b__74_0(IScheduler _, Action a) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at Avalonia.ReactiveUI.AvaloniaScheduler.Schedule[TState](TState state, TimeSpan dueTime, Func`3 action) in /_/src/Avalonia.ReactiveUI/AvaloniaScheduler.cs:line 74
   at System.Reactive.Concurrency.LocalScheduler.Schedule[TState](TState state, Func`3 action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/LocalScheduler.cs:line 32
   at System.Reactive.Concurrency.Scheduler.Schedule(IScheduler scheduler, Action action) in /_/Rx.NET/Source/src/System.Reactive/Concurrency/Scheduler.Simple.cs:line 37
   at ReactiveUI.RxApp.<>c.<.cctor>b__9_1(Exception ex) in /_/src/ReactiveUI/RxApp.cs:line 106
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 561
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 507
   at System.Reactive.ObserveOnObserverNew`1.<>c.<.cctor>b__17_0(IScheduler scheduler, ObserveOnObserverNew`1 self) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 497
   at Avalonia.ReactiveUI.AvaloniaScheduler.<>c__DisplayClass4_1`1.<Schedule>b__1() in /_/src/Avalonia.ReactiveUI/AvaloniaScheduler.cs:line 48
   at Avalonia.Threading.DispatcherOperation.InvokeCore() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 294
   at Avalonia.Threading.DispatcherOperation.Execute() in /_/src/Avalonia.Base/Threading/DispatcherOperation.cs:line 268
   at Avalonia.Threading.Dispatcher.ExecuteJob(DispatcherOperation job) in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 126
   at Avalonia.Threading.Dispatcher.ExecuteJobsCore() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 160
   at Avalonia.Threading.Dispatcher.Signaled() in /_/src/Avalonia.Base/Threading/Dispatcher.Queue.cs:line 134
   at Avalonia.Win32.Win32Platform.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam) in /_/src/Windows/Avalonia.Win32/Win32Platform.cs:line 191
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG& lpmsg)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken cancellationToken) in /_/src/Windows/Avalonia.Win32/Win32DispatcherImpl.cs:line 111
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl impl) in /_/src/Avalonia.Base/Threading/DispatcherFrame.cs:line 117
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame frame) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 53
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.MainLoop.cs:line 80
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 127
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 220
   at Scarab.Program.Main(String[] args) in D:\a\Scarab\Scarab\Scarab\Program.cs:line 28

**Comment by fifty-six** [comment]
Can you try the latest release? I had fixed a bug like this in that one specifically
