### ISSUE TITLE
scarab is dosen't work

### ISSUE THREAD

**Issue by mechenygolovoypocolecheny** [fifty-six/Scarab#235]
### Scarab Version

v2.6.0.0

### Hollow Knight Version

v1.5.78.11833

### Steps to Reproduce

мой скараб не работает ваапще пытаюсь что либо скачять меня посылают нафиг

my scarab is dosen't work, he's don't wanna to download any mods i got a error what should i do?
![image](https://github.com/user-attachments/assets/a65099da-b8c6-4d1f-a4d1-495b3cfcda06)

### Expected Behaviour

i expected i can download any mod but scarab is broken every time and every time i need to fix it, help me

### Actual Behaviour

i open scarab, tap on download api and he's just don't downloading, anythink is not happend, i wanna to download custom knight mod and HKMP and i got a error, every time i don't know what should i need to do, somebody help me

### Logs

2024-12-09 09:30:19.445 +03:00 [INF] Launching...
2024-12-09 09:30:19.746 +03:00 [INF] Initializing to normal mode (.cctor)
2024-12-09 09:30:20.368 +03:00 [INF] Checking if up to date...
2024-12-09 09:30:20.370 +03:00 [INF] Current version of installer is 2.6.0.0
2024-12-09 09:30:20.785 +03:00 [INF] Loading settings.
2024-12-09 09:30:20.791 +03:00 [INF] Trying path D:\Steam/steamapps/common/Hollow Knight\Hollow Knight_Data/Managed
2024-12-09 09:30:20.791 +03:00 [INF] Trying path D:\Steam/steamapps/common/Hollow Knight\hollow_knight_Data/Managed
2024-12-09 09:30:20.792 +03:00 [INF] Found valid path D:\Steam/steamapps/common/Hollow Knight / hollow_knight_Data/Managed
2024-12-09 09:30:20.793 +03:00 [INF] Settings doesn't exist. Creating it at detected path ValidPath { Path = D:\Steam/steamapps/common/Hollow Knight\hollow_knight_Data/Managed, Root = D:\Steam/steamapps/common/Hollow Knight, Suffix = hollow_knight_Data/Managed }.
2024-12-09 09:30:22.161 +03:00 [INF] Fetching links
2024-12-09 09:30:28.179 +03:00 [WRN] Failed with normal client, trying workaround.
2024-12-09 09:30:31.344 +03:00 [INF] Fetched links successfully
2024-12-09 09:30:31.419 +03:00 [INF] Displaying model
2024-12-09 09:30:33.752 +03:00 [INF] Toggling API, current state: NotInstalledState { Installing = False }
2024-12-09 09:30:44.278 +03:00 [INF] Performing "Install" for ModItem { Name: AbsRad Teleport Control, State: NotInstalledState { Installing = False }, Version: 1.1.1.0 }.
2024-12-09 09:30:47.745 +03:00 [INF] Launching...
2024-12-09 09:30:48.034 +03:00 [INF] Initializing to normal mode (.cctor)
2024-12-09 09:30:48.656 +03:00 [INF] Checking if up to date...
2024-12-09 09:30:48.659 +03:00 [INF] Current version of installer is 2.6.0.0
2024-12-09 09:30:49.086 +03:00 [INF] Loading settings.
2024-12-09 09:30:49.109 +03:00 [INF] Fetching links
2024-12-09 09:30:52.296 +03:00 [INF] Fetched links successfully
2024-12-09 09:30:52.373 +03:00 [INF] Displaying model
2024-12-09 09:31:03.827 +03:00 [INF] Performing "Install" for ModItem { Name: Custom Knight, State: NotInstalledState { Installing = False }, Version: 3.1.0.0 }.
2024-12-09 09:32:43.848 +03:00 [ERR] Error when performing "Install" for Custom Knight!
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Scarab.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Scarab\Scarab\Scarab\Util\HttpClientExt.cs:line 16
   at Scarab.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 365
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest, ReinstallPolicy policy) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 168
   at Scarab.Services.Installer.InstallApi(ReinstallPolicy policy) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 141
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 231
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 124
   at Scarab.ViewModels.ModPageViewModel.<>c__DisplayClass76_0.<<InternalUpdateInstallAsync>b__1>d.MoveNext() in D:\a\Scarab\Scarab\Scarab\ViewModels\ModPageViewModel.cs:line 266
--- End of stack trace from previous location ---
   at Scarab.ViewModels.ModPageViewModel.InternalUpdateInstallAsync(ModAction type, ModItem item, Func`3 f) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModPageViewModel.cs:line 266
2024-12-09 09:32:53.128 +03:00 [INF] Performing "Install" for ModItem { Name: Custom Knight, State: NotInstalledState { Installing = False }, Version: 3.1.0.0 }.
2024-12-09 09:34:33.138 +03:00 [ERR] Error when performing "Install" for Custom Knight!
System.Threading.Tasks.TaskCanceledException: The request was canceled due to the configured HttpClient.Timeout of 100 seconds elapsing.
 ---> System.TimeoutException: A task was canceled.
 ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Scarab.Util.HttpClientExt.DownloadBytesWithProgressAsync(HttpClient self, Uri uri, IProgress`1 progress, CancellationToken cts) in D:\a\Scarab\Scarab\Scarab\Util\HttpClientExt.cs:line 16
   at Scarab.Services.Installer.DownloadFile(String uri, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 365
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest, ReinstallPolicy policy) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 168
   at Scarab.Services.Installer.InstallApi(ReinstallPolicy policy) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 141
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 231
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 124
   at Scarab.ViewModels.ModPageViewModel.<>c__DisplayClass76_0.<<InternalUpdateInstallAsync>b__1>d.MoveNext() in D:\a\Scarab\Scarab\Scarab\ViewModels\ModPageViewModel.cs:line 266
--- End of stack trace from previous location ---
   at Scarab.ViewModels.ModPageViewModel.InternalUpdateInstallAsync(ModAction type, ModItem item, Func`3 f) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModPageViewModel.cs:line 266

**Comment by fifty-six** [comment]
Hey, if you download from [this url](https://github.com/hk-modding/api/releases/download/1.5.78.11833-74/ModdingApiWin.zip) does it work fine? Similarly, does [this one](https://github.com/PrashantMohta/HollowKnight.CustomKnight/releases/download/v3.1.0-auto-mr/CustomKnight.zip) work? It's timing out on the download for you currently.

**Comment by mechenygolovoypocolecheny** [comment]
одбой

no i dont need more help, i find a problem with my game folder on scarab logs folder

**Comment by mechenygolovoypocolecheny** [comment]
my HKInstallerSettings is broken, I reinstalled Logs folder but its dosen't help, Fifty-Six can you fix you're path NKinstallersettings  because i need to fix it with my bear hands and this is annoying

**Comment by mechenygolovoypocolecheny** [comment]
![image](https://github.com/user-attachments/assets/e8dfd4b1-58c2-4337-850d-d499f2bb1145)
