### ISSUE TITLE
Scarab Crashing (1.11)

### ISSUE THREAD

**Issue by AstralNarble** [fifty-six/Scarab#61]
My Scarab instantly closes as soon as I open it. I am using the windows version.

**Comment by fifty-six** [comment]
Does it have any logs near it? Can you send the contents of `%appdata%\HKModInstaller\ModInstaller.log` and other logs in that folder? Are you on Windows 7?

**Comment by MeltedUsername** [comment]
im having the same issue it just says "InvalidOperationException: Call from invalid thread"

**Comment by fifty-six** [comment]
Is there any stacktrace before it? Can you give me the entire log file?

**Comment by MeltedUsername** [comment]
System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 535
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 503
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.DoShutdown(ShutdownRequestedEventArgs e, Boolean force, Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 162
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 86
   at Scarab.Program.Handler(PosixSignalContext c) in D:\a\Scarab\Scarab\Scarab\Program.cs:line 42
   at Scarab.Program.<>c.<Main>b__0_0(Object _, EventArgs _) in D:\a\Scarab\Scarab\Scarab\Program.cs:line 23
   at System.AppContext.OnProcessExit()

**Comment by fifty-six** [comment]
try https://github.com/fifty-six/Scarab/suites/6606866848/artifacts/248366313 or the other artifacts (https://github.com/fifty-six/Scarab/actions/runs/2365195414) if you're not on windows

**Comment by MeltedUsername** [comment]
that just looks to be a download for scarab, i open it and it doesnt work :/, also i re tried to install it and stuff but now it just crashes without giving a log

**Comment by fifty-six** [comment]
That one has a few tweaks, should at least have more info to the logging if you use it.

**Comment by MeltedUsername** [comment]
nothing happens, it opens, loads nothing, then closes

**Comment by fifty-six** [comment]
And there's nothing in the ModInstaller.log?

**Comment by MeltedUsername** [comment]
i dont see that file at all

**Comment by fifty-six** [comment]
It should be in `%appdata%\HKModInstaller` to be clear, as I changed the unhandled exception to just logging why it was trying to shut down in the first place.

**Comment by MeltedUsername** [comment]
just error logs

**Comment by fifty-six** [comment]
If you're on windows, can you see if [debugview](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) shows anything?

**Comment by MeltedUsername** [comment]
sorry for taking so long, but no it doesnt show anything

**Comment by fifty-six** [comment]
If you could try [this version](https://files.catbox.moe/axphx1.zip) that would be great.

**Comment by JamiMyst** [comment]
As of Scarab v1.19.0.0/HK v1.5.80.11835, this issue is still occuring. Although this may be because I am on the Xbox Store installation, instead of Steam.

**Comment by fifty-six** [comment]
The game pass version won't work unless you've cloned the install to a different location
