### ISSUE TITLE
exception error 

### ISSUE THREAD

**Issue by ixtee** [fifty-six/Scarab#76]
cant install mods
logs:
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #46544415)
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #59467483)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #65445301)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #52136803)
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24749807)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21421675)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #15271547)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #3226198)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #29035785)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #49143529)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #39638585)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21202951)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #22799085)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #3865173)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #34786562)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #16555740)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #14783937)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #65946577)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #42386454)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #45933772)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #10750772)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #46245228)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #13553869)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #54875957)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #34322009)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #40462633)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #28619382)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #52078584)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #66054074)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57615760)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #53131231)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #8419032)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #8662426)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #13731878)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #56478042)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #38540333)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57767782)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #50147992)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #48678752)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #31815862)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #17907308)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #26948044)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #27806533)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #48932206)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #37736673)
Something sent a shutdown event, calling Application.Shutdown
Got past Application.Shutdown, did shutting down fail?
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #24749807)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21421675)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #58577354)
Something sent a shutdown event, calling Application.Shutdown
Got past Application.Shutdown, did shutting down fail?
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
Fetching links
Fetched links successfully
Building service provider
Built service provider
Displaying model
Failed to install mod Abskoth. State = NotInstalledState { Installing = False }, Link = https://github.com/AngelSassin/Abskoth/releases/download/v1.0/Abskoth.zip
Scarab Error: 0 : System.UnauthorizedAccessException: Access to the path 'F:\xbox fgmaes\Hollow Knight\Content\Hollow Knight_Data\Managed\Assembly-CSharp.dll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Abstractions.FileStreamFactory.Create(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Scarab.Services.Installer.ExtractToFile(ZipArchiveEntry src, String dest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 406
   at Scarab.Services.Installer.ExtractZip(ArraySegment`1 data, String root) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 390
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 167
   at Scarab.Services.Installer.InstallApi() in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 135
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 222
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 119
   at Scarab.ViewModels.ModListViewModel.InternalUpdateInstallAsync(ModItem item, Func`3 f) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 204
    DateTime=2022-05-23T08:53:40.4813600Z
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #64305901)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #41882197)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #41395459)
Failed to install mod Abskoth. State = NotInstalledState { Installing = False }, Link = https://github.com/AngelSassin/Abskoth/releases/download/v1.0/Abskoth.zip
Scarab Error: 0 : System.UnauthorizedAccessException: Access to the path 'F:\xbox fgmaes\Hollow Knight\Content\Hollow Knight_Data\Managed\Assembly-CSharp.dll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Abstractions.FileStreamFactory.Create(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Scarab.Services.Installer.ExtractToFile(ZipArchiveEntry src, String dest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 406
   at Scarab.Services.Installer.ExtractZip(ArraySegment`1 data, String root) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 390
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 167
   at Scarab.Services.Installer.InstallApi() in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 135
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 222
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 119
   at Scarab.ViewModels.ModListViewModel.InternalUpdateInstallAsync(ModItem item, Func`3 f) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 204
    DateTime=2022-05-23T16:15:36.2218023Z
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #31069492)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #11189975)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #33600918)
Failed to install mod BingoUI. State = NotInstalledState { Installing = False }, Link = https://github.com/flibber-hk/HollowKnight.BingoUI/releases/download/v2.1.2.2/BingoUI.zip
Scarab Error: 0 : System.UnauthorizedAccessException: Access to the path 'F:\xbox fgmaes\Hollow Knight\Content\Hollow Knight_Data\Managed\Assembly-CSharp.dll' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at System.IO.Abstractions.FileStreamFactory.Create(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean useAsync)
   at Scarab.Services.Installer.ExtractToFile(ZipArchiveEntry src, String dest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 406
   at Scarab.Services.Installer.ExtractZip(ArraySegment`1 data, String root) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 390
   at Scarab.Services.Installer._InstallApi(ValueTuple`3 manifest) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 167
   at Scarab.Services.Installer.InstallApi() in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 135
   at Scarab.Services.Installer.Install(ModItem mod, Action`1 setProgress, Boolean enable) in D:\a\Scarab\Scarab\Scarab\Services\Installer.cs:line 222
   at Scarab.Models.ModItem.OnInstall(IInstaller inst, Action`1 setProgress) in D:\a\Scarab\Scarab\Scarab\Models\ModItem.cs:line 119
   at Scarab.ViewModels.ModListViewModel.InternalUpdateInstallAsync(ModItem item, Func`3 f) in D:\a\Scarab\Scarab\Scarab\ViewModels\ModListViewModel.cs:line 204
    DateTime=2022-05-23T16:17:49.6824338Z
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #42052973)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #42932445)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #50847687)

**Comment by fifty-six** [comment]
Ah yeah, Xbox/Game pass/Microsoft Store games don't support mods because you can't write over files. If you want to mod the game you'll need it on some other platform.
