### ISSUE TITLE
scarab doesnt work

### ISSUE THREAD

**Issue by Chris12354** [fifty-six/Scarab#93]
### Scarab Version

v.1.16.0.0

### Hollow Knight Version

dont know 

### Steps to Reproduce

dont know

### Expected Behaviour

dont know

### Actual Behaviour

my scarab opens, stays 3 seconds, blackscreen,closes and then an error appears in my files (yestedary it was working)

### Logs

dont know

**Comment by Chris12354** [comment]
please help my scarab opens then closes,error appears in my file and thats it (yestedary it worked)

**Comment by fifty-six** [comment]
Please attach the error, I can't really do anything without more info. Did you check the folder with logs? Does it exist?

**Comment by Chris12354** [comment]
System.InvalidOperationException: Call from invalid thread
   at Avalonia.Threading.Dispatcher.VerifyAccess() in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 48
   at Avalonia.Controls.Window.CloseInternal() in /_/src/Avalonia.Controls/Window.cs:line 535
   at Avalonia.Controls.Window.Close(Boolean ignoreCancel) in /_/src/Avalonia.Controls/Window.cs:line 503
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.DoShutdown(ShutdownRequestedEventArgs e, Boolean force, Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 162
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Shutdown(Int32 exitCode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 86
   at Scarab.Program.Handler(PosixSignalContext c) in D:\a\Scarab\Scarab\Scarab\Program.cs:line 42
   at Scarab.Program.<>c.<Main>b__0_0(Object _, EventArgs _) in D:\a\Scarab\Scarab\Scarab\Program.cs:line 23
   at System.AppContext.OnProcessExit()

**Comment by Chris12354** [comment]
this is the error

**Comment by fifty-six** [comment]
No I need the one in `%appdata%\HKModInstaller`

**Comment by Chris12354** [comment]
Launching...
[OpenGL] Unable to initialize EGL-based rendering: 'System.DllNotFoundException: Dll was not found.
   at Avalonia.OpenGL.Angle.AngleEglInterface.EGL_GetProcAddress(String proc)
   at Avalonia.OpenGL.Angle.AngleEglInterface.LoadAngle() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 21
   at Avalonia.OpenGL.Angle.AngleEglInterface..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleEglInterface.cs:line 12
   at Avalonia.OpenGL.Angle.AngleWin32EglDisplay..ctor() in /_/src/Avalonia.OpenGL/Angle/AngleWin32EglDisplay.cs:line 65
   at Avalonia.Win32.Win32GlManager.<>c.<Initialize>b__0_1() in /_/src/Windows/Avalonia.Win32/Win32GlManager.cs:line 25
   at Avalonia.OpenGL.Egl.EglPlatformOpenGlInterface.TryCreate(Func`1 displayFactory) in /_/src/Avalonia.OpenGL/Egl/EglPlatformOpenGlInterface.cs:line 34'
LogHost: Initializing to normal mode (.cctor)
Checking if up to date...
Loading settings.
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57434139)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #47145209)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #21653700)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #20917673)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #54041329)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #16609919)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #57656175)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #49143529)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #39638585)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #2533231)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #22799085)
[Binding] Error in binding to 'Avalonia.Input.KeyBinding'.'Command': 'Null value in expression '{empty}' at ''.' (KeyBinding #3865173)
Something sent a shutdown event, calling Application.Shutdown
Got past Application.Shutdown, did shutting down fail?

**Comment by Chris12354** [comment]
this one???

**Comment by fifty-six** [comment]
Can you try the newest release?

**Comment by Chris12354** [comment]
I dont really know wich one is the new release, I got this from a friend

**Comment by Chris12354** [comment]
nvm found it

**Comment by Chris12354** [comment]
tysm

**Comment by fifty-six** [comment]
Does this mean it works now?
